### ISSUE TITLE
Data for Seoul, South Korea 

### ISSUE THREAD

**Issue by cdkang** [winstonyym/urbanity#3]
Hello, 

It is very impressive to share Urbanity for urban studies and planning. 

I want to study the case of Seoul, Korea for my own research. 

Could you let know how to get the relevant data or how to make it? 

Sincerely,

**Comment by winstonyym** [comment]
@cdkang thank you for your kind interest. To the best of my knowledge, open data is quite challenging to acquire in Seoul. For example, open building footprints and street view imagery is not so comprehensive. You can check out [Mapillary](https://www.mapillary.com/app/) to see the distribution of street view images available for Seoul. 

Nonetheless, while the core of Urbanity is made for open data, we are also working on features to automatically integrate (non-open) data into our package. We understand that planners might have access to such private data but would still like to use Urbanity. If such a situation applies to you, you can include links to the dataset that you are looking at and I will include it into the development pipeline for Urbanity.

**Comment by ghost** [comment]
Thank you for your swift and kind information. Sincerely.
