### ISSUE TITLE
Environment.yml does not entirely used conda-forge

### ISSUE THREAD

**Issue by Ultios** [winstonyym/urbanity#5]
OS : Windows 10 Education.

Detailed to reproduce bug

(base) PS C:\Users\maman\Documents\PhD\Urbanity> conda env create -f environment.yml

Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

I think it is because urbanity itself is not hosted on conda-forge, hosting it on conda-forge and changing the environment may make the installation simpler.

**Comment by winstonyym** [comment]
Thank you for this suggestion. Will update again when Urbanity is hosted on conda-forge.
