### ISSUE TITLE
stuck at solving environment 

### ISSUE THREAD

**Issue by Ultios** [winstonyym/urbanity#6]
OS: Windows 10 Education

after failing once and installing visual c++, a fresh new install is stuck at solving environment.

will try https://stackoverflow.com/questions/63734508/stuck-at-solving-environment-on-anaconda , I think it also happens in osmnx.
Meanwhile I will try installation in my macbook.

**Comment by Ultios** [comment]
OS: MacOs Ventura 13.3.1

Installation also stuck at solving environment.

Both OS windows and mac is solved by using the strict priority channel command

`conda config --set channel_priority strict`

It will be useful to add this in the installation readme

**Comment by winstonyym** [comment]
@Ultios thank you very much for identifying this issue and also for providing the installation solution. I include this in the readme instructions.
